documentation:
  - docs/**/*
  - README.md

examples:
  - flash_examples/**/*

data:
  - flash/core/data/**/*

task:
  - flash/tabular/**/*
  - flash/text/**/*
  - flash/image/**/*
  - flash/video/**/*

tabular:
  - flash/tabular/**/*

text:
  - flash/text/**/*

vision:
  - flash/image/**/*
  - flash/video/**/*
